module.exports = function(app) {
    const User = require('./User')
    const MobileProjects = require('./MobileProjects')
    const InternalDocuments = require('./InternalDocuments')
    const MobileProjectSpecs = require('./MobileProjectSpecs')
    const MobileProjectInfo = require('./MobileProjectInfo')
    const MobileProjectStoreInfo = require('./MobileProjectStoreInfo')
    const MobileProjectsMeetingNote = require('./MobileProjectsMeetingNote')
    const AppSpecDocs = require('./AppSpecDocs')
    User(app)
    MobileProjects(app)
    InternalDocuments(app)
    MobileProjectSpecs(app)
    AppSpecDocs(app)
    MobileProjectInfo(app)
    MobileProjectStoreInfo(app)
    MobileProjectsMeetingNote(app)
}